---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: frontend-gateway
# Allow traffic from frontend-gateway to frontend
spec:
  destination:
    name: frontend
  sources:
    - name: frontend-gateway
      action: allow
