apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "consul-gateway.router" . }}
  labels:
    {{- include "consul-gateway.labels" . | nindent 4 }}
spec:
  # Defines the gateway listener.
  parentRefs:
  - name: {{ include "consul-gateway.fullname" . }}
  # Rules define behaviors for network traffic that goes through the route.
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    # Defines the backend service.
    backendRefs:
    - kind: Service
      name: {{ .Values.frontend.svc.name }}
      namespace: {{ .Values.appNamespace }}
      port: {{ .Values.frontend.svc.port }}
