apiVersion: v1
kind: Secret
metadata:
  name: {{ include "frontend.imagePullSecret.name" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "frontend.imagePullSecret" . }}
