apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  destination:
    name: {{ .Values.backend.name }}
  sources:
    - name: {{ include "frontend.fullname" . }}
      action: allow
