apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "backend.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: JWT_TOKEN
            valueFrom:
              secretKeyRef:
                name: schedule-app-secrets
                key: secret-jwt-token
          - name: JWT_EXPIRED
            valueFrom:
              secretKeyRef:
                name: schedule-app-secrets
                key: secret-jwt-expired

          - name: POSTGRES_DATABASE
            valueFrom:
              secretKeyRef:
                name: schedule-app-secrets
                key: secret-postgres-db
          - name: POSTGRES_URL
            valueFrom:
              secretKeyRef:
                name: schedule-app-secrets
                key: secret-postgres-url
          - name: POSTGRES_ADMIN
            valueFrom:
              secretKeyRef:
                name: schedule-app-secrets
                key: secret-postgres-admin
          - name: POSTGRES_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: schedule-app-secrets
                key: secret-postgres-password

          - name: REDIS_URL
            valueFrom:
              secretKeyRef:
                name: schedule-app-secrets
                key: secret-redis-url

          - name: MONGO_DATABASE
            valueFrom:
              secretKeyRef:
                name: schedule-app-secrets
                key: secret-mongo-db
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                name: schedule-app-secrets
                key: secret-mongo-url

          - name: SMTP_HOST
            valueFrom:
              secretKeyRef:
                name: schedule-app-secrets
                key: secret-smtp-host
          - name: SMTP_USERNAME
            valueFrom:
              secretKeyRef:
                name: schedule-app-secrets
                key: secret-smtp-password
          - name: SMTP_PASSOWRD
            valueFrom:
              secretKeyRef:
                name: schedule-app-secrets
                key: secret-smtp-username
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
