apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.name }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshTime }}          
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.secretStore.name }}  
  target:
    name: {{ .Values.externalSecrets.targetName }}
    creationPolicy: Owner
  data:
    {{- include "backend.externalSecrets.EnvirnomentsMapping" . | nindent 4 }}
