apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretStore.vaultProvider.secretToken.name }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  {{- include "backend.secretStore.secretToken" . | nindent 2 }}
