apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  labels:
{{- include "backend.labels" . | nindent 4 }}
spec:
  provider:
{{- with .Values.secretStore.vaultProvider }}
    vault:
      server: {{ .server }}
      path: {{ .path }}
      version: {{ .version }}
      auth:
{{- with .auth }}
        appRole:
          path: {{ .method }}
          roleId: {{ .roleId }}
          secretRef:
            name: {{ .secret.name }}
            key: {{ .secret.key }}
{{- end }}
{{- end }}
