apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretStore.vaultProvider.auth.secret.name }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  {{- include "backend.secretStore.appRoleSecret" . | nindent 2 }}
