apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: gcp-secrets-sync
spec:
  secretObjects:
  - secretName: schedule-app-secrets
    type: Opaque
    data: 
    - objectName: "JWT_TOKEN"
      key: secret-jwt-token
    - objectName: "JWT_EXPIRED"
      key: secret-jwt-expired
    - objectName: "POSTGRES_DATABASE"
      key: secret-postgres-db
    - objectName: "POSTGRES_URL"
      key: secret-postgres-url
    - objectName: "POSTGRES_ADMIN"
      key: secret-postgres-admin
    - objectName: "POSTGRES_ADMIN_PASSWORD"
      key: secret-postgres-password
    - objectName: "MONGO_DATABASE"
      key: secret-mongo-db
    - objectName: "MONGO_URL"
      key: secret-mongo-url
    - objectName: "REDIS_URL"
      key: secret-redis-url
    - objectName: "SMTP_HOST"
      key: secret-smtp-host
    - objectName: "SMTP_PASSOWRD"
      key: secret-smtp-password
    - objectName: "SMTP_USERNAME"
      key: secret-smtp-username
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/224639746902/secrets/JWT_TOKEN/versions/1"
        path: "JWT_TOKEN"
      - resourceName: "projects/224639746902/secrets/JWT_EXPIRED/versions/1"
        path: "JWT_EXPIRED"
      - resourceName: "projects/224639746902/secrets/POSTGRES_DATABASE/versions/1"
        path: "POSTGRES_DATABASE"
      - resourceName: "projects/224639746902/secrets/POSTGRES_URL/versions/1"
        path: "POSTGRES_URL"
      - resourceName: "projects/224639746902/secrets/POSTGRES_ADMIN/versions/1"
        path: "POSTGRES_ADMIN"
      - resourceName: "projects/224639746902/secrets/POSTGRES_ADMIN_PASSWORD/versions/1"
        path: "POSTGRES_ADMIN_PASSWORD"
      - resourceName: "projects/224639746902/secrets/MONGO_DATABASE/versions/1"
        path: "MONGO_DATABASE"
      - resourceName: "projects/224639746902/secrets/MONGO_URL/versions/1"
        path: "MONGO_URL"
      - resourceName: "projects/224639746902/secrets/REDIS_URL/versions/1"
        path: "REDIS_URL"
      - resourceName: "projects/224639746902/secrets/SMTP_HOST/versions/1"
        path: "SMTP_HOST"
      - resourceName: "projects/224639746902/secrets/SMTP_PASSOWRD/versions/1"
        path: "SMTP_PASSOWRD"
      - resourceName: "projects/224639746902/secrets/SMTP_USERNAME/versions/1"
        path: "SMTP_USERNAME"
