{{- $serviceAccountName := .Values.gcp.k8sServiceAccount.name -}}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  labels:
{{- include "backend.labels" . | nindent 4 }}
spec:
  provider:
{{- with .Values.gcp }}
    gcpsm:
      projectID: {{ .projectId }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .cluster.location }}
          clusterName: {{ .cluster.name }}
          serviceAccountRef:
            name: {{ $serviceAccountName }}
{{- end }}
