apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.imagePullSecret.name" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "backend.imagePullSecret" . }}
