apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: {{ include "backend.fullname" . }}
spec:
  destination:
    name: backend-redis-master
  sources:
    - name: {{ include "backend.fullname" . }}
      action: allow
