---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: frontend
  namespace: schedule-app
# Allow traffic from frontend to backend
spec:
  destination:
    name: backend
  sources:
    - name: frontend
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: backend
  namespace: schedule-app
# Allow traffic from frontend to backend
spec:
  destination:
    name: backend-redis-master
  sources:
    - name: backend
      action: allow
