apiVersion: consul.hashicorp.com/v1alpha1
kind: ExportedServices
metadata:
  name: default ## The name of the partition containing the service
  namespace: schedule-app
spec:
  services:
    - name: backend ## The name of the service you want to export
      consumers:
      - peer: azure ## The name of the peering connection that receives the service
