apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: azure-frontend-to-gcp-backend
  namespace: schedule-app
spec:
  destination:
    name: backend
  sources:
   - name: frontend
     action: allow
     peer: azure
