apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: backend
  namespace: schedule-app
spec:
  connectTimeout: 15s
  failover:
    '*':
      targets:
        - peer: gcp
